name: Fetch Sheet & Images

# Only manual trigger
on:
  workflow_dispatch:

jobs:
  build-content:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install requests

      # 4️⃣ Run the fetch_data.py script
      - name: Fetch Sheet & Download Images
        run: python fetch_data.py

      # 5️⃣ Commit updated JSON & images
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json images/
          git commit -m "Update sheet data and images" || echo "No changes to commit"
          git push
